### ISSUE TITLE
Compile error when compiling grammar that uses IGNORECASE

### ISSUE THREAD

**Issue by dualarrow** [marat1961/Oz-CocoR-Delphi#8]
Hi,

1st, great parser !

When you have IGNORECASED in your grammar, it creates 2 compile errors in the resulting scanner. I fixed them with the following but I can't tell if this is the correct fix or not

oz.cocor.dfa  Line 1600

from          gen.WriteLine('  if ch <> Buffer.EOF then');
to              gen.WriteLine('  if ch <> #26 then');

Line 1603 from   gen.WriteLine('    ch := char.ToLower(char(ch));');
to                       gen.WriteLine('    ch := character.ToLower(char(ch));');

Scanner.frame needs to add

uses
  character;

in implementation

**Comment by marat1961** [comment]
Thank you for reporting this bug.
Also found that not all updates were committed.

**Comment by marat1961** [comment]
fixed
